version: '3'
services:
  app:
    environment:
      DB_USER: postgres
      DB_NAME: postgres
      DB_HOST: db
      DB_PASSWORD: LocalPassword
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      # [Optional] You can use build args to set options. e.g. 'VARIANT' below affects the image in the Dockerfile
      args:
        VARIANT: 0.35.1

    volumes:
      - ..:/workspace

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    links:
      - db

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: LocalPassword
